name: Add Cart
on:
  workflow_dispatch:
    inputs:
      itemId:
        description: "Item ID for PayPayMall"
        required: true
        type: string

jobs:
  add-cart:
    name: Add Item to Cart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nanasess/setup-chromedriver@v1.0.5
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: pipenv
      - name: Install Japanese Fonts
        run: |
          sudo apt install -y fonts-ipafont
          fc-cache -fv
          fc-list | grep -i ipa
      - name: Install dependencies
        run: pipenv install
      - name: Start XVFB
        run: Xvfb :99 &
      - name: Add Cart
        env:
          DISPLAY: :99
          TZ: Asia/Tokyo
          YAHOO_ID: ${{ secrets.YAHOO_ID }}
          YAHOO_PASSWORD: ${{ secrets.YAHOO_PASSWORD }}
          LOHACO_ITEM_ID: ${{ github.event.inputs.itemId }}
        run: pipenv run add_cart
