name: Generate JSON File
on:
  push:
    branches: [main]

jobs:
  generate_json:
    name: Generate JSON Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen

      - name: Add Cart
        env:
          TZ: "Asia/Tokyo"
        run: uv run generate_json.py

      - name: Commit files
        run: |
          git add --all
          git commit -m "[skip ci] Update ./items/* files" || echo "Nothing to update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
