name: Generate JSON File
on:
  push:
    branches:
      - main

jobs:
  generate_json:
    name: Generate JSON Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pipenv
        run: pipx install pipenv
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: pipenv
      - name: Install dependencies
        run: pipenv install
      - name: Add Cart
        env:
          TZ: "Asia/Tokyo"
        run: pipenv run generate_json
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "[skip ci] Update ./items/* files" || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
